export const ISLOGIN = 'ISLOGIN'; //是否登录
export const USERID = 'USERID'; //用户UserId
export const IMGURL = 'IMGURL'; //用户UserId
export const UUID = 'UUID'; //用户UUID
export const NO = 'NO'; //模拟用户NO
export const TOKEN = 'TOKEN'; //用户token
export const SOFTKEYBOARD = 'SOFTKEYBOARD'; //软键盘状态
export const USERINFO = 'USERINFO'; //用户信息
export const USERNAME = 'USERNAME'; // 用户昵称
export const LOADINGFLAG = 'LOADINGFLAG'; //loading的状态
export const CARVINS = 'CARVINS'; //vin车辆编码
export const SELECTLABELSTATE = 'SELECTLABELSTATE'; //选择的频道
export const TSP = 'TSP'; //查询tsp用户的信息
export const NONAME = 'NONAME'; //智享首页储存的no和name
export const MOBILESTATUSBAR = 'MOBILESTATUSBAR'; //手机状态栏高度,原生提供
export const QRCODEPIN = 'QRCODEPIN'; //扫描二维码获取的vin,用于扫一扫判断
export const GETWORDS = 'GETWORDS'; //获取各种提示
export const RECORD = 'RECORD'; //记录wit部分页面跳转
export const CHANGE_$FLAG = 'CHANGE_$FLAG' // 有用别动
export const RECORDNO = 'RECORDNO' // 网点评价成功后的RECORDNO
// export const NOMARLSERISENAME = 'NOMARLSERISENAME' // 爱车页面默认的seriseName
export const DEFAULTINFORMATION = 'DEFAULTINFORMATION' // 默认车辆的所有信息
export const POSITION = 'POSITION' // 默认车辆的所有信息
